# Generated by Django 5.2.14 on 2026-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('triggered', 'Disparada'), ('paused', 'Pausada')], default='active', max_length=10)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
