# Generated by Django 5.2.14 on 2026-05-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial_marketplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('product_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='catalog.producturl')),
            ],
            options={
                'verbose_name': 'clic de afiliado',
                'verbose_name_plural': 'clics de afiliado',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
