# Generated by Django 5.2.14 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_affiliateclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('discount_type', models.CharField(choices=[('percent', '% descuento'), ('fixed', '€ fijo'), ('free_shipping', 'Envío gratis')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_order', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='catalog.marketplace')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-created_at'],
            },
        ),
    ]
