# Generated by Django 5.2.14 on 2026-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_referenceproduct_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='affiliate_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='producturl',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
